/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pcte;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.net.ftp.FTPClient;
import static pcte.Conexao.Conectar;
import static pcte.Conexao.con;


/**
 *
 * @author Usuario
 */
public class Arquivos extends javax.swing.JPanel {

    /**
     * Creates new form Arquivos
     */
    public Arquivos() {
        initComponents();
        Conectar();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        txtUrl = new javax.swing.JTextField();
        txtDiretorio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnProcurar = new javax.swing.JButton();
        BtnEnviar = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        foto = new javax.swing.JLabel();

        jLabel1.setText("URL");

        jLabel2.setText("Diretório");

        BtnProcurar.setText("Procurar");
        BtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcurarActionPerformed(evt);
            }
        });

        BtnEnviar.setText("Enviar");
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });

        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUrl)
                            .addComponent(txtDiretorio, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnProcurar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnEnviar))
                            .addComponent(BtnSair))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(BtnProcurar)
                    .addComponent(BtnEnviar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BtnSair))
                .addGap(18, 18, 18)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcurarActionPerformed
        File arquivo;
        String nome_arq = null;
        BufferedImage imagem;
        
        
        FC.setFileFilter(
        new FileNameExtensionFilter(
        "Arquivo de imagem(JPG, PNG, PDF, TXT)",
        "png","jpg","txt","pdf")
                );
        
        FC.setAcceptAllFileFilterUsed(false);
        
        if (FC.showOpenDialog(null)==0){
            arquivo = FC.getSelectedFile();
            txtDiretorio.setText(nome_arq);
            try{
                imagem = ImageIO.read(arquivo);
                ImageIcon icon = new ImageIcon(
                imagem.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH));
                foto.setIcon(icon);
            }catch(IOException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_BtnProcurarActionPerformed

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        try{
        FTPClient ftp = new FTPClient();
        ftp.connect("127.0.0.1");
        ftp.login("Teste","1234");
        ftp.setFileType(FTPClient.BINARY_FILE_TYPE);
        
        FileInputStream arqEnviar = new FileInputStream(txtUrl.getText());
         if(ftp.storeFile(txtDiretorio.getText(),arqEnviar)){
             System.out.println("Arquivo armazenado com sucesso");
         }else{
             System.out.println("Erro ao armazenar o arquivo!");
         }
        }
        catch(IOException e){
            System.out.println("Erro ao armazenar o arquivo"); 
        }
        
    }//GEN-LAST:event_BtnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JButton BtnProcurar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel foto;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDiretorio;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
