/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pcte;

import javax.swing.JOptionPane;
import static pcte.Conexao.con;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import static pcte.Conexao.Conectar;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author Usuario
 */
public class Consultar extends javax.swing.JFrame {

    
    /**
     * Creates new form consultar
     */
    public Consultar() {
        initComponents();
        Conectar();
        setLocationRelativeTo(null);
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        JLdataehora.setText(agora.format(formato));
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlTelf = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        TxTel = new javax.swing.JTextField();
        TxCpf = new javax.swing.JTextField();
        TxNome = new javax.swing.JTextField();
        JbConsul = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TxCep = new javax.swing.JTextField();
        TxRg = new javax.swing.JTextField();
        TxEndereco = new javax.swing.JTextField();
        TxPais = new javax.swing.JTextField();
        TxCel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JButton();
        BtnArq = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        JLdataehora = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNome.setText("Nome");

        jlCpf.setText("CPF");

        jlTelf.setText("Telefone");

        jlCidade.setText("Cidade");

        JbConsul.setText("Consultar");
        JbConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsulActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setMaximumSize(new java.awt.Dimension(81, 23));
        jbSalvar.setMinimumSize(new java.awt.Dimension(81, 23));
        jbSalvar.setPreferredSize(new java.awt.Dimension(81, 23));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setMaximumSize(new java.awt.Dimension(81, 23));
        jbExcluir.setMinimumSize(new java.awt.Dimension(81, 23));
        jbExcluir.setPreferredSize(new java.awt.Dimension(81, 23));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel1.setText("CEP");

        jLabel2.setText("RG");

        jLabel3.setText("Endereço");

        jLabel4.setText("Pais");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        jLabel5.setText("Celular");

        jLabel6.setText("Estado");

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        BtnArq.setText("Arquivo");
        BtnArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnArqActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcte/_fazer_download_do_arquivo.png"))); // NOI18N
        jLabel8.setText(" ");

        JLdataehora.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbConsul)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BtnArq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 10, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlCpf)
                                            .addComponent(jLabel2)
                                            .addComponent(jlNome))
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jlTelf)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel1)
                                            .addComponent(jlCidade)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(29, 29, 29)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxEstado)
                                    .addComponent(TxCel)
                                    .addComponent(TxNome)
                                    .addComponent(TxCidade)
                                    .addComponent(TxTel)
                                    .addComponent(TxCpf)
                                    .addComponent(TxCep)
                                    .addComponent(TxRg)
                                    .addComponent(TxEndereco)
                                    .addComponent(TxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLdataehora)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnArq, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTelf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbConsul)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar)
                    .addComponent(jbSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLdataehora)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsulActionPerformed
        String usuario = TxNome.getText();

        try{
            String sql = "SELECT * FROM consulta WHERE nome like ?";
            PreparedStatement stm = con.prepareStatement(sql);
            stm.setString(1,"%"+usuario+"%");
            ResultSet rs = stm.executeQuery();

            if(rs.next()){
                TxNome.setText(rs.getString("Nome"));
                TxCpf.setText(rs.getString("CPF"));
                TxTel.setText(rs.getString("Telefone"));
                TxCidade.setText(rs.getString("Cidade"));
                TxCep.setText(rs.getString("CEP"));
                TxRg.setText(rs.getString("RG"));
                TxEndereco.setText(rs.getString("Endereço"));
                TxPais.setText(rs.getString("Pais"));
                TxCel.setText(rs.getString("Celular"));
                TxEstado.setText(rs.getString("Estado"));
                
            
            }
            else{
                JOptionPane.showMessageDialog(null,"Usuario não encontrado!", null, 3);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Erro ao conectar:"+ ex.getMessage());
        }

    }//GEN-LAST:event_JbConsulActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        
        int result, opcao;
        String sql;
        Object[] options = {"Sim", "Não"};
        opcao = JOptionPane.showOptionDialog(null,"Você Confirma a exclusão?","Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,options[1]);
        jbExcluir.setEnabled(false);
        JbConsul.setEnabled(false);
        jbSalvar.setEnabled(false);
        
        if(opcao == 0){
            
            try{
                sql = "delete from consulta where nome = ?";
                PreparedStatement stm = con.prepareStatement(sql,
                    ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE
                    );
                stm.setString(1, TxNome.getText());
                
                result = stm.executeUpdate();
                if(result>0){
                    boolean resultado = stm.execute();
                    System.out.println(resultado);
                    if(stm.execute()==false){
                        JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso!");
                     
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Erro ao excluir!");
                    }
                    
                }
            }catch(SQLException e)
            {
                    JOptionPane.showMessageDialog(null, "Erro!" + e);
            }
        }
        
        
        
        
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        int result;
        String sql, Nome, CPF, Telefone, Cidade, CEP, RG, Endereço, Pais, Celular, Estado;

        Nome = TxNome.getText();
        CPF = TxCpf.getText();
        Telefone = TxTel.getText();
        Cidade = TxCidade.getText();
        CEP = TxCpf.getText();
        RG = TxRg.getText();
        Endereço = TxEndereco.getText();
        Pais  = TxPais.getText();
        Celular = TxCel.getText();
        Estado = TxEstado.getText();

        try{
            sql = "insert into consulta( Nome, CPF, Telefone, Cidade, CEP, RG, Endereço, Pais, Celular, Estado) values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(sql);

            stm.setString(1, Nome);
            stm.setString(2, CPF);
            stm.setString(3, Telefone);
            stm.setString(4, Cidade);
            stm.setString(5, CEP);
            stm.setString(6, RG);
            stm.setString(7, Endereço);
            stm.setString(8, Pais);
            stm.setString(9, Celular);
            stm.setString(10, Estado);

            TxNome.setText("");
            TxCpf.setText("");
            TxTel.setText("");
            TxCidade.setText("");
            TxCep.setText("");
            TxRg.setText("");
            TxEndereco.setText("");
            TxPais.setText("");
            TxCel.setText("");
            TxEstado.setText("");
            TxNome.requestFocus();

            result = stm.executeUpdate();
            if(result > 0)
            {
                JOptionPane.showMessageDialog(null, "Dados Gravados com Sucesso");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Erro ao inserir dados");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro!" + e);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
            TxNome.setText("");
            TxCpf.setText("");
            TxTel.setText("");
            TxCidade.setText("");
            TxCep.setText("");
            TxRg.setText("");
            TxEndereco.setText("");
            TxPais.setText("");
            TxCel.setText("");
            TxEstado.setText("");
            TxNome.requestFocus();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void BtnArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnArqActionPerformed
                Arquivo arq = new Arquivo();
                arq.setVisible(true);  
                       
    }//GEN-LAST:event_BtnArqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnArq;
    private javax.swing.JLabel JLdataehora;
    private javax.swing.JButton JbConsul;
    private javax.swing.JTextField TxCel;
    private javax.swing.JTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JTextField TxCpf;
    private javax.swing.JTextField TxEndereco;
    private javax.swing.JTextField TxEstado;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxPais;
    private javax.swing.JTextField TxRg;
    private javax.swing.JTextField TxTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelf;
    // End of variables declaration//GEN-END:variables
}
